### ISSUE TITLE
WJoy foohid

### ISSUE THREAD

**Issue by eestein** [JustinBis/CS50x#1]
Hi, I'm posting here because you have disabled issues on https://github.com/JustinBis/wjoy-foohid

Are you still working on that? I found a bug, but I don't want to report it in case you dropped the development.

Thanks.

**Comment by JustinBis** [comment]
Just enabled issues tracking for wjoy-foohid, feel free to tag the issue there. The project isn't under active development, but maybe someone in the future will want to work to update it.
